### ISSUE TITLE
Cropper not working on mobile

### ISSUE THREAD

**Issue by jbojcic1** [MartijnW49/ngx-image-cropper#2]
Currently cropper is not working on mobile because in this case startMove is called after moveImg. I see touchmove and touchend events so I guess the plan was to support that and this is a bug?

To see the issue, you can use chrome mobile simulator

**Comment by jbojcic1** [comment]
I created a PR in which you can see how we supported touch devices. For now it works only for one finger but that's better than nothing. If you think it has any value, merge it

**Comment by shijithkm** [comment]
Any update here , I am also looking for the same

**Comment by jbojcic1** [comment]
@shijithkm I fixed this in my fork but I supported only gestures with one finger for now. If that's ok for you you can take that.

**Comment by shijithkm** [comment]
Thanks Josip , actually i have installed this plugin using "npm install ngx-image-cropper --save"  this command , how can i use yours , please help.

**Comment by jbojcic1** [comment]
@shijithkm I don't have npm package. You can use it from github by including it in your package.json:
"ngx-image-cropper": "git://git@github.com:jbojcic1/ngx-image-cropper.git"

**Comment by MartijnW49** [comment]
Sorry for the late reply, seems like my notification settings are not setup correctly..
It seems I did indeed forget to add the touchstart events.
I added them and made a new release to npm, 0.1.13!

@jbojcic1 Is there a reason why you removed the touch-action css in your code? It seems to stop firing the warnings about preventDefault being called.

**Comment by jbojcic1** [comment]
@MartijnW49 I removed it to prevent that warning. Is there some reason why you want to keep that warning?

**Comment by jbojcic1** [comment]
@MartijnW49 also I increased cropper markers height and width on mobile as I think default size is too small for gestures which makes it hard to use on mobile devices.
