### ISSUE TITLE
Output format not changing to .jpg

### ISSUE THREAD

**Issue by jaleesB** [MartijnW49/ngx-image-cropper#4]
I have changed the format attribute="jpg" in my html. But the resultant image is always png. Jpg images are also being converted into png. Please tell any solution.

**Comment by MartijnW49** [comment]
Hi jaleesB

I did some research and if you want to use jpg, you should set the format to 'jpeg'.
Not all browsers support all filetypes, but png is always supported.
FireFox and Chrome both do support jpeg luckily, but older versions of IE for example will propably not.
I updated the readme and the image cropper as well so it will only accept the following filetypes: 'png' | 'jpeg' | 'bmp' | 'webp' | 'ico'.
If you choose a filetype that isn't supported, it will automatically switch to png again which is what happened when you chose the 'jpg' format.

Thanks for reporting ;)
