### ISSUE TITLE
How to reset the cropper?

### ISSUE THREAD

**Issue by AmirGilboa** [MartijnW49/ngx-image-cropper#5]
I'm using this component to crop an image before uploading. it works fine.
but after uploading, i want to let the user upload another image.
the previous image is still loaded, and that is undesirable. I want it to be empty, 
just like the first time. Any idea how to achieve that? tnx.

**Comment by MartijnW49** [comment]
Hi, I made a new release 0.1.14 on npm. 
It should solve your problem!
Let me know how it goes ;)

**Comment by AmirGilboa** [comment]
That's great, thank you!
but... I don't see any change in the api/doc, so is there a new command that i should call to reset the component, or will it happen by itself? then when?

**Comment by MartijnW49** [comment]
If you set `imageChangedEvent` to `null` now, it will remove the image that was loaded. If you choose a new image, it will remove the old one immediately instead of waiting until the new image is loaded.

**Comment by AmirGilboa** [comment]
Yes, it works! wow, thanks!

**Comment by UNADYNE** [comment]
But if you change the imageChangedEvent to null and choose the same file again the fileChangedEvent is not fired.

Possible use case is that the user accidentally removes the file he wants to upload and tries to re upload.

How can I get around this?

**Comment by MartijnW49** [comment]
This is because the file input itself doesn't change, so it will not fire a "change" event. If you reset that input's value, then you'll be able to choose the same image again. You can do so by setting the value of the file input to null. I used @ViewChild to get a reference to the input field, not sure whether it'll work with ngModel or a FormControl.

**Comment by karloscode** [comment]
@Mawi137  this works for me: 
    this.inputImage.nativeElement.value = null;
thanks a lot for your help.
