### ISSUE TITLE
请帮助我

### ISSUE THREAD

**Issue by lw664256297** [MartijnW49/ngx-image-cropper#6]
请问下，如何设置初始化默认图片？

**Comment by MartijnW49** [comment]
I don't speak Chinese, but Google did a good job translating this ;)
Now, you can either use the `imageChangedEvent` property to load an image from a file input (an example can be found in the ReadMe.md). Or you can use the `imageBase64` property to load a Base64 image directly.

**Comment by lw664256297** [comment]
谢谢你伙计，你救了我一命 ：）
